module Views.BottomBar exposing (view)

import Html exposing (..)
import Html.Attributes exposing (..)


view : Html msg
view =
    div [ class "BottomBar" ]
        [ div [ class "Player" ]
            [ div [ class "Player__controls" ]
                [ button [] [ i [ class "icon-play" ] [] ]
                , button [] [ i [ class "icon-to-start" ] [] ]
                , button [] [ i [ class "icon-to-end" ] [] ]
                ]
            , div [ class "PlayerCurrent" ]
                [ img [ class "PlayerCurrent__cover", src "https://i.scdn.co/image/ab67616d0000b273d10a2159dc6ef7beb9ef098e" ] []
                , div [ class "PlayerCurrent__controls" ]
                    [ div []
                        [ span [ class "PlayerCurrent__song" ] [ text "The Proving Grounds" ]
                        , span [] [ text " - " ]
                        , a [ href "", class "Artist__link" ] [ text "Mars Red Sky" ]
                        ]
                    , input [ class "PlayerCurrent__range", type_ "range" ] []
                    ]
                ]
            ]
        , div [ class "Device" ]
            [ div [ class "Device__select" ]
                [ i [ class "Device__active icon-computer" ] []
                , div [ class "DeviceList" ]
                    [ div [ class "DeviceListHead" ]
                        [ div []
                            [ i [ class "DeviceListHead__icon1 icon-smartphone" ] []
                            , i [ class "DeviceListHead__icon2 icon-computer" ] []
                            , i [ class "DeviceListHead__icon3 icon-speaker" ] []
                            ]
                        , text "Choose the device on which to play your music"
                        ]
                    , div [ class "DeviceList__item active" ]
                        [ div [ class "DeviceList__icon" ] [ i [ class "icon-computer" ] [] ]
                        , div []
                            [ div [ class "Device__name" ] [ text "Machin" ]
                            , div [ class "Device__id" ] [ text "DellXPS 15" ]
                            ]
                        ]
                    , div [ class "DeviceList__item" ]
                        [ div [ class "DeviceList__icon" ] [ i [ class "icon-speaker" ] [] ]
                        , div []
                            [ div [ class "Device__name" ] [ text "Machin" ]
                            , div [ class "Device__id" ] [ text "DellXPS 15" ]
                            ]
                        ]
                    ]
                ]
            , div [ class "Device__volume" ] [ i [ class "icon-sound" ] [], input [ type_ "range" ] [] ]
            ]
        ]
