module Views.Sidebar exposing (view)

import Html exposing (..)
import Html.Attributes exposing (..)


view : Html msg
view =
    div [ class "Sidebar" ]
        [ div [ class "Sidebar__item" ]
            [ h2 [ class "Sidebar__title Heading" ] [ text "Collections" ]
            , div [ class "Sidebar__collections HelperScrollArea" ]
                [ ul [ class "HelperScrollArea__target List unstyled" ]
                    [ li [ class "List__item" ] [ i [ class "List__icon icon-collection" ] [], text "Collection 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-collection" ] [], text "Collection 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-collection" ] [], text "Collection 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-collection" ] [], text "Collection 1" ]
                    , li [ class "List__item active" ] [ i [ class "List__icon icon-collection" ] [], text "Collection 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-collection" ] [], text "Collection 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-collection" ] [], text "Collection 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-collection" ] [], text "Collection 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-collection" ] [], text "Collection 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-collection" ] [], text "Collection 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-collection" ] [], text "Collection 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-collection" ] [], text "Collection 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-collection" ] [], text "Collection 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-collection" ] [], text "Collection 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-collection" ] [], text "Collection 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-collection" ] [], text "Collection 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-collection" ] [], text "Collection 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-collection" ] [], text "Collection 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-collection" ] [], text "Collection 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-collection" ] [], text "Collection 1" ]
                    ]
                ]
            ]
        , div [ class "Sidebar__item" ]
            [ h2 [ class "Sidebar__title Heading" ] [ text "Playlists" ]
            , div [ class "Sidebar__playlists HelperScrollArea" ]
                [ ul [ class "HelperScrollArea__target List unstyled" ]
                    [ li [ class "List__item" ] [ i [ class "List__icon icon-music" ] [], text "playlist 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-music" ] [], text "playlist 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-music" ] [], text "playlist 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-music" ] [], text "playlist 1" ]
                    , li [ class "List__item active" ] [ i [ class "List__icon icon-music" ] [], text "playlist 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-music" ] [], text "playlist 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-music" ] [], text "playlist 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-music" ] [], text "playlist 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-music" ] [], text "playlist 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-music" ] [], text "playlist 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-music" ] [], text "playlist 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-music" ] [], text "playlist 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-music" ] [], text "playlist 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-music" ] [], text "playlist 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-music" ] [], text "playlist 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-music" ] [], text "playlist 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-music" ] [], text "playlist 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-music" ] [], text "playlist 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-music" ] [], text "playlist 1" ]
                    , li [ class "List__item" ] [ i [ class "List__icon icon-music" ] [], text "playlist 1" ]
                    ]
                ]
            ]
        ]
