module Page.Artist exposing (view)

import Html exposing (..)
import Html.Attributes exposing (..)


view : Html msg
view =
    div [ class "Flex fullHeight" ]
        [ div [ class "Flex__full HelperScrollArea" ]
            [ div [ class "Artist__body HelperScrollArea__target" ]
                [ div [ class "Flex spaceBetween centeredVertical" ]
                    [ h1 [ class "Heading first" ] [ text "Pain of Salvation" ]
                    , button [ class "Button big" ] [ text "Follow" ]
                    ]
                , div [ class "Artist__links External" ]
                    [ a [ class "External__item", href "#" ] [ i [ class "External__icon icon-wikipedia" ] [], text "Wikipedia" ]
                    , a [ class "External__item", href "#" ] [ i [ class "External__icon icon-sputnik" ] [], text "Sputnik" ]
                    , a [ class "External__item", href "#" ] [ i [ class "External__icon icon-discogs" ] [], text "Discogs" ]
                    , a [ class "External__item", href "#" ] [ i [ class "External__icon icon-magnifying-glass" ] [], text "Google" ]
                    ]
                , div [ class "Artist__top" ]
                    [ div []
                        [ h2 [ class "Heading second" ] [ text "Top tracks" ]
                        , div [ class "Track Flex centeredVertical" ]
                            [ img [ class "Track__cover", src "https://i.scdn.co/image/ab67616d00004851b6db1b15fbf0d6a11de4b13c" ] []
                            , div [ class "Track__name Flex__full" ] [ text "Sisters" ]
                            , div [ class "Track__duration" ] [ text "6:15" ]
                            ]
                        , div [ class "Track Flex centeredVertical" ]
                            [ img [ class "Track__cover", src "https://i.scdn.co/image/ab67616d00004851a45cd272063bc487a0615791" ] []
                            , div [ class "Track__name Flex__full" ] [ text "Meaningless" ]
                            , div [ class "Track__duration" ] [ text "4:47" ]
                            ]
                        , div [ class "Track Flex centeredVertical" ]
                            [ img [ class "Track__cover", src "https://i.scdn.co/image/ab67616d000048513ef2598ca7bf8c4c9d317b9e" ] []
                            , div [ class "Track__name Flex__full" ] [ text "Undertow" ]
                            , div [ class "Track__duration" ] [ text "4:47" ]
                            ]
                        , div [ class "Track Flex centeredVertical" ]
                            [ img [ class "Track__cover", src "https://i.scdn.co/image/ab67616d00004851a45cd272063bc487a0615791" ] []
                            , div [ class "Track__name Flex__full" ] [ text "Silent Gold" ]
                            , div [ class "Track__duration" ] [ text "3:23" ]
                            ]
                        , div [ class "Track Flex centeredVertical" ]
                            [ img [ class "Track__cover", src "https://i.scdn.co/image/ab67616d00004851a45cd272063bc487a0615791" ] []
                            , div [ class "Track__name Flex__full" ] [ text "On a Thuesday" ]
                            , div [ class "Track__duration" ] [ text "10:22" ]
                            ]
                        ]
                    , div [ class "ArtistSimilar" ]
                        [ h2 [ class "Heading second" ] [ text "Similar artists" ]
                        , a [ class "ArtistSimilar__item", href "#" ]
                            [ img [ class "ArtistSimilar__avatar", src "https://i.scdn.co/image/ab67616d000048517308edb16e889fb03e0c06f7" ] []
                            , span [ class "ArtistSimilar__name" ] [ text "OSI" ]
                            ]
                        , a [ class "ArtistSimilar__item", href "#" ]
                            [ img [ class "ArtistSimilar__avatar", src "https://i.scdn.co/image/ab67616d00004851b5a802ad72225f03178099b6" ] []
                            , span [ class "ArtistSimilar__name" ] [ text "Guilt Machine" ]
                            ]
                        , a [ class "ArtistSimilar__item", href "#" ]
                            [ img [ class "ArtistSimilar__avatar", src "https://i.scdn.co/image/6ec60563bca6acd50f6b3ef73d4121bdb769dd33" ] []
                            , span [ class "ArtistSimilar__name" ] [ text "Riverside" ]
                            ]
                        , a [ class "ArtistSimilar__item", href "#" ]
                            [ img [ class "ArtistSimilar__avatar", src "https://i.scdn.co/image/481d1a97b7e67220d1ab3613f5f5bab2c671f047" ] []
                            , span [ class "ArtistSimilar__name" ] [ text "Ayreon" ]
                            ]
                        ]
                    ]
                , div []
                    [ h2 [ class "Heading second" ] [ text "Albums" ]
                    , div [ class "Artist__releaseList AlbumList" ]
                        [ div [ class "Album" ]
                            [ a [ class "Album__link", href "#" ]
                                [ img [ class "Album__cover", src "https://i.scdn.co/image/ab67616d00001e02a45cd272063bc487a0615791" ] []
                                , button [ class "Album__play" ] [ i [ class "icon-play" ] [] ]
                                , button [ class "Album__add" ] [ i [ class "icon-add" ] [] ]
                                ]
                            , div [ class "Album__name" ] [ text "In The Passing Light of Day" ]
                            , div [ class "Album__release" ] [ text "(2017)" ]
                            ]
                        , div [ class "Album" ]
                            [ a [ class "Album__link", href "#" ]
                                [ img [ class "Album__cover", src "https://i.scdn.co/image/ab67616d00001e026112c09de48809873488eb97" ] []
                                , button [ class "Album__play" ] [ i [ class "icon-play" ] [] ]
                                , button [ class "Album__add" ] [ i [ class "icon-add" ] [] ]
                                ]
                            , div [ class "Album__name" ] [ text "Remedy Lane Re:lived" ]
                            , div [ class "Album__release" ] [ text "(2016)" ]
                            ]
                        , div [ class "Album" ]
                            [ a [ class "Album__link", href "#" ]
                                [ img [ class "Album__cover", src "https://i.scdn.co/image/ab67616d00001e02951a174f717e2b4fb57c90ef" ] []
                                , button [ class "Album__play" ] [ i [ class "icon-play" ] [] ]
                                , button [ class "Album__add" ] [ i [ class "icon-add" ] [] ]
                                ]
                            , div [ class "Album__name" ] [ text "Remedy Lane Re:mixed" ]
                            , div [ class "Album__release" ] [ text "(2016)" ]
                            ]
                        , div [ class "Album" ]
                            [ a [ class "Album__link", href "#" ]
                                [ img [ class "Album__cover", src "https://i.scdn.co/image/ab67616d00001e02749c330ea008a87fb3f19dd1" ] []
                                , button [ class "Album__play" ] [ i [ class "icon-play" ] [] ]
                                , button [ class "Album__add" ] [ i [ class "icon-add" ] [] ]
                                ]
                            , div [ class "Album__name" ] [ text "Falling Home" ]
                            , div [ class "Album__release" ] [ text "(2014)" ]
                            ]
                        , div [ class "Album" ]
                            [ a [ class "Album__link", href "#" ]
                                [ img [ class "Album__cover", src "https://i.scdn.co/image/ab67616d00001e02c2d2935f63289fc4d2785b3d" ] []
                                , button [ class "Album__play" ] [ i [ class "icon-play" ] [] ]
                                , button [ class "Album__add" ] [ i [ class "icon-add" ] [] ]
                                ]
                            , div [ class "Album__name" ] [ text "Road Salt Two" ]
                            , div [ class "Album__release" ] [ text "(2011)" ]
                            ]
                        , div [ class "Album" ]
                            [ a [ class "Album__link", href "#" ]
                                [ img [ class "Album__cover", src "https://i.scdn.co/image/ab67616d00001e02b6db1b15fbf0d6a11de4b13c" ] []
                                , button [ class "Album__play" ] [ i [ class "icon-play" ] [] ]
                                , button [ class "Album__add" ] [ i [ class "icon-add" ] [] ]
                                ]
                            , div [ class "Album__name" ] [ text "Road Salt One" ]
                            , div [ class "Album__release" ] [ text "(2010)" ]
                            ]
                        ]
                    ]
                , div []
                    [ h2 [ class "Heading second" ] [ text "EPs" ]
                    , div [ class "Artist__releaseList AlbumList" ]
                        [ div [ class "Album" ]
                            [ a [ class "Album__link", href "#" ]
                                [ img [ class "Album__cover", src "https://i.scdn.co/image/ab67616d00001e02b6db1b15fbf0d6a11de4b13c" ] []
                                , button [ class "Album__play" ] [ i [ class "icon-play" ] [] ]
                                , button [ class "Album__add" ] [ i [ class "icon-add" ] [] ]
                                ]
                            , div [ class "Album__name" ] [ text "Road Salt One" ]
                            , div [ class "Album__release" ] [ text "(2010)" ]
                            ]
                        , div [ class "Album" ]
                            [ a [ class "Album__link", href "#" ]
                                [ img [ class "Album__cover", src "https://i.scdn.co/image/ab67616d00001e02b6db1b15fbf0d6a11de4b13c" ] []
                                , button [ class "Album__play" ] [ i [ class "icon-play" ] [] ]
                                , button [ class "Album__add" ] [ i [ class "icon-add" ] [] ]
                                ]
                            , div [ class "Album__name" ] [ text "Road Salt One" ]
                            , div [ class "Album__release" ] [ text "(2010)" ]
                            ]
                        , div [ class "Album" ]
                            [ a [ class "Album__link", href "#" ]
                                [ img [ class "Album__cover", src "https://i.scdn.co/image/ab67616d00001e02b6db1b15fbf0d6a11de4b13c" ] []
                                , button [ class "Album__play" ] [ i [ class "icon-play" ] [] ]
                                , button [ class "Album__add" ] [ i [ class "icon-add" ] [] ]
                                ]
                            , div [ class "Album__name" ] [ text "Road Salt One" ]
                            , div [ class "Album__release" ] [ text "(2010)" ]
                            ]
                        ]
                    ]
                , div []
                    [ h2 [ class "Heading second" ] [ text "Singles" ]
                    , div [ class "Artist__releaseList AlbumList" ]
                        [ div [ class "Album" ]
                            [ a [ class "Album__link", href "#" ]
                                [ img [ class "Album__cover", src "https://i.scdn.co/image/ab67616d00001e02951a174f717e2b4fb57c90ef" ] []
                                , button [ class "Album__play" ] [ i [ class "icon-play" ] [] ]
                                , button [ class "Album__add" ] [ i [ class "icon-add" ] [] ]
                                ]
                            , div [ class "Album__name" ] [ text "Road Salt One" ]
                            , div [ class "Album__release" ] [ text "(2010)" ]
                            ]
                        , div [ class "Album" ]
                            [ a [ class "Album__link", href "#" ]
                                [ img [ class "Album__cover", src "https://i.scdn.co/image/ab67616d00001e02951a174f717e2b4fb57c90ef" ] []
                                , button [ class "Album__play" ] [ i [ class "icon-play" ] [] ]
                                , button [ class "Album__add" ] [ i [ class "icon-add" ] [] ]
                                ]
                            , div [ class "Album__name" ] [ text "Road Salt One" ]
                            , div [ class "Album__release" ] [ text "(2010)" ]
                            ]
                        ]
                    ]
                ]
            ]
        , div [ class "Artist__videos HelperScrollArea" ]
            [ div [ class "Video HelperScrollArea__target" ]
                [ h2 [ class "Heading second" ] [ text "Last videos" ]
                , div [ class "Video__item" ]
                    [ iframe [ class "Video__embed", src "https://www.youtube.com/embed/MreXYqelGPM", width 230, height 130 ] []
                    , div [ class "Video__name" ] [ text "Pain Of Salvation - Meaningless (official video)" ]
                    , a [ href "#", class "Video__channel Link" ] [ text "painofsalvationVEVO" ]
                    ]
                , div [ class "Video__item" ]
                    [ iframe [ class "Video__embed", src "https://www.youtube.com/embed/MreXYqelGPM", width 230, height 130 ] []
                    , div [ class "Video__name" ] [ text "Pain Of Salvation - Meaningless (official video)" ]
                    , a [ href "#", class "Video__channel Link" ] [ text "painofsalvationVEVO" ]
                    ]
                , div [ class "Video__item" ]
                    [ iframe [ class "Video__embed", src "https://www.youtube.com/embed/MreXYqelGPM", width 230, height 130 ] []
                    , div [ class "Video__name" ] [ text "Pain Of Salvation - Meaningless (official video)" ]
                    , a [ href "#", class "Video__channel Link" ] [ text "painofsalvationVEVO" ]
                    ]
                , div [ class "Video__item" ]
                    [ iframe [ class "Video__embed", src "https://www.youtube.com/embed/MreXYqelGPM", width 230, height 130 ] []
                    , div [ class "Video__name" ] [ text "Pain Of Salvation - Meaningless (official video)" ]
                    , a [ href "#", class "Video__channel Link" ] [ text "painofsalvationVEVO" ]
                    ]
                , div [ class "Video__item" ]
                    [ iframe [ class "Video__embed", src "https://www.youtube.com/embed/MreXYqelGPM", width 230, height 130 ] []
                    , div [ class "Video__name" ] [ text "Pain Of Salvation - Meaningless (official video)" ]
                    , a [ href "#", class "Video__channel Link" ] [ text "painofsalvationVEVO" ]
                    ]
                ]
            ]
        ]



-- <iframe class="PageArtistVideo__video" allowfullscreen="" frameborder="0" width="250" height="140" src="https://www.youtube.com/embed/MreXYqelGPM"></iframe>
