import store from "./store";
import axios from "axios";

//  Generated by https://example-app.com/pkce
const cv = "7e5b934e584a8f27e0af01231ddaebdcb69e3033ee26db48fe1892fd";
const cvHasedBase64url = "t5oGiJ2QcE9rK1WdE6yUQA_5tquXc3ijSWx8F5c18s0";

export const api = {
  url: "https://api.spotify.com/",
  clientId: "29a0936f4c6c46399f33f6f60a0855e8",
  clientSecret: "7d50fed5ac154883ae4d5eec1138a3f2",
  redirectUri:
    process.env.NODE_ENV !== "production" ? "http://localhost:3000/auth" : "https://orchestre.netlify.app/auth",
  codeVerifier: cv,
  codeChallenge: cvHasedBase64url,
  scopes:
    "user-read-private%20user-modify-playback-state%20user-read-playback-state%20user-read-currently-playing%20playlist-read-private%20playlist-read-collaborative%20playlist-modify-private%20playlist-modify-public%20user-follow-modify%20user-follow-read%20streaming%20user-read-email",
};

export const instance = axios.create({
  baseURL: api.url + "v1/",
  timeout: 1000,
  headers: {
    Authorization: `Bearer ${store.state.auth.auth.accessToken}`,
    "Content-Type": "application/json",
  },
});
export const instanceAuth = axios.create({
  baseURL: "https://accounts.spotify.com/api/",
  timeout: 1000,
  headers: {
    Authorization: `Bearer ${store.state.auth.auth.accessToken}`,
    "Content-Type": "application/x-www-form-urlencoded",
  },
});

export const connectUrl = `https://accounts.spotify.com/authorize?response_type=code&client_id=${api.clientId}&redirect_uri=${api.redirectUri}&scope=${api.scopes}&code_challenge_method=S256&code_challenge=${api.codeChallenge}`;
